import sys
from io import StringIO
from Simulador import main

def simulate_input(inputs):
    sys.stdin = StringIO(inputs)
    main()
    sys.stdin = sys.__stdin__

# Test para verificar que el programa se ejecute correctamente
if __name__ == "__main__":
    inputs = """\
DEFINIR PROGRAMA fibonacci LOCAL
DEFINIR PROGRAMA fibonacci LOCAL
EJECUTABLE fibonacci
DEFINIR PROGRAMA factorial Java
EJECUTABLE factorial
DEFINIR INTERPRETE C Java
DEFINIR INTERPRETE c Java
DEFINIR TRADUCTOR C Java C
DEFINIR TRADUCTOR C Java C
EJECUTABLE factorial
DEFINIR INTERPRETE LOCAL C
EJECUTABLE factorial
DEFINIR PROGRAMA holamundo Python3
DEFINIR TRADUCTOR wtf42 Python3 LOCAL
EJECUTABLE holamundo
DEFINIR TRADUCTOR C wtf42 Java
EJECUTABLE holamundo
DEFINIR PROGRAMA prueba C++
DEFINIR TRADUCTOR LOCAL C++ PERL
DEFINIR TRADUCTOR JS PERL KOTLIN
DEFINIR TRADUCTOR LOCAL JS PASCAL
DEFINIR TRADUCTOR LOCAL PASCAL SHELL
DEFINIR INTERPRETE LOCAL SHELL
DEFINIR INTERPRETE LOCAL KOTLIN
EJECUTABLE prueba
DEFINIR PROGRAMA prueba2 CSS
DEFINIR TRADUCTOR HTML CSS JS
DEFINIR TRADUCTOR LOCAL HTML ICON
DEFINIR TRADUCTOR LOCAL ICON LOCAL
DEFINIR INTERPRETE LOCAL JS
EJECUTABLE prueba2
DEFINIR PROGRAMA prueba3 RANDOM
DEFINIR TRADUCTOR DDOS RANDOM LOCAL
DEFINIR TRADUCTOR MYSQL DDOS LENGUAJE
DEFINIR INTERPRETE LOCAL MYSQL
EJECUTABLE prueba3
DEFINIR PROGRAMA prueba4 HTML
DEFINIR INTERPRETE JS HTML
EJECUTABLE prueba4
DEFINIR PROGRAMA prueba5 YARN
DEFINIR TRADUCTOR LOCAL YARN JS
EJECUTABLE prueba5
DEFINIR PROGRAMA prueba6 DOCKER
DEFINIR TRADUCTOR JS DOCKER PYTHON
EJECUTABLE prueba6
DEFINIR PROGRAMA prueba7 JOSE
DEFINIR TRADUCTOR SSH JOSE SHELL
DEFINIR TRADUCTOR LOCAL SHELL OPENSSL
EJECUTABLE prueba7
ayuda
SALIR
"""
    simulate_input(inputs)